"""add subjects lesions measurements

Revision ID: 107080725261
Revises: bf67dd8773cb
Create Date: 2026-02-13 17:25:28.005373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107080725261'
down_revision = 'bf67dd8773cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age_at_diagnosis', sa.Integer(), nullable=True),
    sa.Column('cancer_type', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'subject_code', name='uq_subject_project_code')
    )
    op.create_index(op.f('ix_subjects_project_id'), 'subjects', ['project_id'], unique=False)
    op.create_table('lesions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('lesion_label', sa.String(length=50), nullable=False),
    sa.Column('anatomic_site', sa.String(length=100), nullable=True),
    sa.Column('laterality', sa.String(length=10), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'lesion_label', name='uq_lesion_subject_label')
    )
    op.create_index(op.f('ix_lesions_subject_id'), 'lesions', ['subject_id'], unique=False)
    op.create_table('lesion_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesion_id', sa.Integer(), nullable=False),
    sa.Column('timepoint', sa.String(length=30), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('longest_diameter_mm', sa.Float(), nullable=False),
    sa.Column('short_axis_mm', sa.Float(), nullable=False),
    sa.Column('volume_mm3', sa.Float(), nullable=True),
    sa.Column('mean_hu', sa.Float(), nullable=True),
    sa.Column('suv_max', sa.Float(), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.CheckConstraint('longest_diameter_mm >= 0', name='ck_longest_diameter_nonneg'),
    sa.CheckConstraint('short_axis_mm >= 0', name='ck_short_axis_nonneg'),
    sa.ForeignKeyConstraint(['lesion_id'], ['lesions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesion_id', 'timepoint', name='uq_measurement_lesion_timepoint')
    )
    op.create_index(op.f('ix_lesion_measurements_lesion_id'), 'lesion_measurements', ['lesion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesion_measurements_lesion_id'), table_name='lesion_measurements')
    op.drop_table('lesion_measurements')
    op.drop_index(op.f('ix_lesions_subject_id'), table_name='lesions')
    op.drop_table('lesions')
    op.drop_index(op.f('ix_subjects_project_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
